#!/bin/bash

echo -e "\033[34m测试 SMTP 中... \033[0m"
sendEmail \
    -f $SMTP_FROM_EMAIL \
    -s $SMTP_MAILER_HOST \
    -t $SMTP_TO_EMAIL \
    -xu $SMTP_MAILER_USER \
    -xp $SMTP_MAILER_PASSWORD \
    -o tls=$SMTP_TLS \
    -u ASP Mial \
    -m 这是一件测试邮件 \
    This is a test email \
    -o message-content-type=html \
    -o message-charset=utf-8
echo