#!/bin/bash

echo -e "\033[34m测试 Telegram Bot 中... \033[0m"
curl -s -k "https://api.telegram.org/bot$TGBOT_SEND_TOKEN/sendMessage" \
    --data-urlencode "chat_id=$TGBOT_SEND_CHATID" \
    --data-urlencode "text=这是一条测试消息 This is a test message"
echo