#!/bin/bash

echo
date
sendEmail \
	-f $SMTP_FROM_EMAIL \
	-s $SMTP_MAILER_HOST \
	-t $SMTP_TO_EMAIL \
	-xu $SMTP_MAILER_USER \
	-xp $SMTP_MAILER_PASSWORD \
	-o tls=$SMTP_TLS \
	-u ASP Mial \
	-m 设置权限成功 \
	Set permissions successfully \
	-o message-content-type=html \
	-o message-charset=utf-8
echo
echo