#!/bin/bash

echo
date
curl -s -k "https://api.telegram.org/bot$TGBOT_SEND_TOKEN/sendMessage" \
	--data-urlencode "chat_id=$TGBOT_SEND_CHATID" \
	--data-urlencode "text=设置权限成功 Set permissions successfully"
echo
echo